# Generated by Django 4.0.2 on 2022-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_remove_sign_user_sign_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='course',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
